### ISSUE TITLE
Label-block not working

### ISSUE THREAD

**Issue by drew0036** [drew0036/volunteer-form#1]
Hi @muxlowc! 

I'm having trouble getting my checkboxes to be on their own line. I keep trying block and label-block, but the checkbox inline-block seems to be over-riding it all. Please, advise. Thank you!

Cheers,
- Holly

**Comment by muxlowc** [comment]
@drew0036 So you need to add a second unit to break up the two columns. So the first unit should include digging holes/getting dirty/lifting heavy objects/driving people, and the other 4 items will be in the second unit. (each unit will be 1-2 on larger screen sizes, which will get them to go side-by-side)

I would also put every label/input couple into their own div like so:

```
<div class="grid">
  <div class="unit xs-1 s-1 m-1-2 l-1-2">
    <div>
      <input type="checkbox" id="digging" name="digging">
      <label for="digging">Digging holes</label>
    </div>
    <div>
      <input type="checkbox" id="dirt" name="dirt">
      <label for="dirt">Getting dirty</label>
    </div>
....
```

**Comment by drew0036** [comment]
Thank you!
