### ISSUE TITLE
Markbot Speaking Nonsense

### ISSUE THREAD

**Issue by drew0036** [drew0036/volunteer-form#2]
@muxlowc 

Hey, I'm not understanding this feedback from Markbot, can you please translate? Thank you!

![Screen Shot 2020-03-21 at 3 31 08 PM](https://user-images.githubusercontent.com/55107709/77235087-504aea80-6b89-11ea-8e4a-0c15f39d3f24.png)

**Comment by muxlowc** [comment]
@drew0036 so what it's saying is that you have too many label's for license - you currently have an extra label where you actually need a legend (which will be inside of a fieldset)

What you currently have:
```
<label class="push" for="license">Do you have a valid driver’s license?</label>
<input type="radio" id="license" name="license">
<label for="license">Yes</label>
<input type="radio" id="license-no" name="license-no">
<label for="license-no">No</label>
```

What it should be :
```
<fieldset>
        <legend>Do you have a valid driver’s license?</legend>

<input type="radio" id="license-yes" name="license">
<label for="license-yes">Yes</label>
<input type="radio" id="license-no" name="license">
<label for="license-no">No</label>
```

**Comment by drew0036** [comment]
Thank you!
